---
# - name: Create a Selenium Grid Server
#   ec2:
#     key_name: grid
#     instance_type: "{{ ec2_instance_type }}"
#     image: "{{ ec2_free_aws_linux }}"
#     wait: yes
#     count: "{{ selenium_grid }}"
#     region: "{{ aws_region }}"
#   register: ec2_instance

# - name: Wait for SSH
#   wait_for:
#     host: "{{ ec2_instance['instances'][0]['public_ip'] }}"
#     port: 22
#     delay: 10
#     timeout: 420
#     state: started
#   with_items: ec2_instance.results

# - name: Wait a little longer for centos
#   pause: seconds=20

# - name: add grid server host to inventory
#   add_host: 
#     name:  "{{ ec2_instance['instances'][0]['public_ip'] }}"
#     groups: "grid_server"
#     ansible_ssh_host: "{{ ec2_instance['instances'][0]['public_ip'] }}"
#     ansible_ssh_private_key_file: '{{ pem_path }}'
#     ansible_ssh_user: "ec2-user"
#     ec2_vars: "{{ ec2_instance['instances'][0] }}"
#     ec2_instance_ids: "{{ ec2_instance['instance_ids'] }}"
#   with_indexed_items: ec2_instances1
           
# - name: Create a Selenium Grid Nodes
#   ec2:   
#     key_name: grid
#     instance_type: "{{ ec2_instance_type }}"
#     image: "{{ ec2_free_win_server_2016 }}"
#     wait: yes
#     count: "{{ selenium_grid_nodes }}"
#     region: "{{ aws_region }}"
#   register: ec2_instance_node

- name: Get the Default Ec2 Windows Admin password
  ec2_win_password:
    profile: my_boto_profile
    # instance_id: "{{ ec2_instance_node['instance_ids'][0] }}"
    instance_id: "i-081324a11bcf5e830"
    key_file: "{{ pem_path }}"
    # region: "{{ aws_region }}"
    region: "eu-west-1"
    wait: yes
  register: ec2_win_pass  

- name: add grid nodes host to inventory
  add_host: 
    name: "{{ ec2_instance_node['instances'][0]['public_ip'] }}"
    groups: "grid_node"
    ansible_ssh_host: "{{ ec2_instance['instances'][0]['public_ip'] }}"
    ansible_user: "Administrator"
    ansible_password: "{{ ec2_win_pass }}"
  with_indexed_items: ec2_instances2   

# - name: set the data
#   debug: 
#     msg: "Grid is {{ ec2_instance }} and Node is {{ ec2_instance_node }}"

